/// <reference types="nativewind/types" />

/**
 * Declares CSS side-effect imports, used by the NativeWind entry stylesheet.
 *
 * The same declaration ships in `expo/types`, reached through `expo-env.d.ts`,
 * but that file is generated by the Expo CLI and is not versioned. Declaring it
 * here keeps `tsc --noEmit` passing on a fresh clone, before any Expo command
 * has run.
 */
declare module '*.css';
